### ISSUE TITLE
PNG naming convention

### ISSUE THREAD

**Issue by blinry** [nordlicht/nordlicht#43]
In the long run, it doesn't make sense that video players have to generate the moodbars anew each time the user opens a video. I suggest the following convention:
- The tool defaults to create the file `VIDEOFILE.nordlicht.png` (for example, `big-buck-bunny.mkv.nordlicht.png`)
- Video players use this file, if it exists. Otherwise, they generate it on the fly.

I actually implemented this in the current master – the tool generates these files by default, and the mpv plugin uses them if they exist. Also, users can trigger a rebuild of the nordlicht in mpv using `N` (for example, if they want another style). This seems pracital, but I'm wondering whether placing the PNGs in the same directory as the video files is too "aggressive" and clutters the users' file structure (one could also put them into `~/.local/share/nordlicht/cache/`, or similar).

Also, one could think of making the file ending more general than this project – like `moodbar.png` or similar – so other "moodbar generating" libraries could use the same convention. This is closely related to how the output images actually should be called, see #28.

What do you think?

**Comment by blinry** [comment]
Yeah, putting them directly in the videos' directory annoys me already. They should go into `$XDG_CAHE_HOME/nordlicht/` (which defaults to `~/.cache/nordlicht/`), and be accessed in a similar fashion to thumbnails. Freedesktop's [Thumbnail Managing Standard](http://specifications.freedesktop.org/thumbnail-spec/thumbnail-spec-latest.html) is pretty close to what we need here.

**Comment by rohieb** [comment]
On 01.02.2016 21:43, Sebastian Morr wrote:
> Yeah, putting them directly in the videos' directory annoys me already. They
> should go into |$XDG_CAHE_HOME/nordlicht/| (which defaults to
> |~/.cache/nordlicht/|), and be accessed in a similar fashion to thumbnails.
> Freedesktop's Thumbnail Managing Standard
> <http://specifications.freedesktop.org/thumbnail-spec/thumbnail-spec-latest.html> is
> pretty close to what we need here.

Seems reasonable to me.

**Comment by aleksejrs** [comment]
Since generating the file takes time, and styles are very different, I'd like to store more than one file per video (at least until I delete the worst ones).  It could be relevant in the script for MPV, which supports choice of a style, but currently uses only one existing nordlicht file.

Something like
* "file.ogv.nordlicht-vertical.png"
* "file.ogv.nordlicht.s-vertical.png"
* "file.ogv.nordlicht.style-vertical.png"

A possible problem could be with file names becoming too long.

**Comment by aleksejrs** [comment]
While style is the most obvious property that can change, width/height are also important (can't stretch a small thumbnail into a good slitscan search bar).

For start/end, I only know MPlayers' EDL and .conf file formats, all of which are tied to a file (the video file or an .edl file), so the nordlicht file name is IMO not a place for this.

**Comment by rohieb** [comment]
@blinry, what do you think of @aleksejrs' suggestion?

**Comment by blinry** [comment]
In 338f713d07f011912bff90af3d439588cfd17987, I went for the easiest solution for now: In mpv-nordlicht, the timebars are saved at `$XDG_CACHE_HOME/nordlicht/(md5sum of filename property).png`.

**Comment by aleksejrs** [comment]
> In 338f713, I went for the easiest solution for now: In mpv-nordlicht, the timebars are saved at $XDG_CACHE_HOME/nordlicht/(md5sum of filename property).png.

I don't like that change:

1. Because of the md5, renaming a video will cause re-generation. Slitscan mode, for example, is very slow.
2. Because of the cache directory, moving the video to a different user will cause re-generation.
3. It doesn't use the existing .nordlicht.png files generated by the previous version.
4. Having the nordlicht near the video makes it easy to copy or send them both.
5. I sometimes use nordlichts to compare similar videos (when editing, or when downloading several versions encoded differently).  Or, I can use one nordlicht for several videos.
