### ISSUE TITLE
MPV Lua plugin should avoid putting the images in world-readable places.

### ISSUE THREAD

**Issue by aleksejrs** [nordlicht/nordlicht#51]
nordlicht 0.4.4.  Because of the umask, the /tmp/nordlicht.bgra file was created world-readable.

**Comment by blinry** [comment]
Didn't think about that, but I totally agree! I guess when we have figured out the naming conventions (#43), these temporary images should be created somewhere around there, too.

**Comment by rohieb** [comment]
Uh yeah. Putting the .bgra in `/tmp` makes all sorts of multi-process usage impossible :-) I guess the nordlicht output itself is worthy to be cached since it is sometimes time-consuming to generate it. But to generate the .bgra for mpv, we only need a (relatively) short `convert`, and it doesn't hurt to do that on the fly, so I'd rather put that one into `/tmp` and delete it afterwards so it doesn't clutter the user's folders.
